### PR TITLE
An optimisation of _PrintNormalFont

### PR DESCRIPTION
**Pull request by grosged**
"Unrolled" in 3 parts in order to have less comparisons inside main loop.

### CODE REVIEW

**Comment by mateoconlechuga** [comment]
You have some typos that the checks found. Please be sure to fix! Thanks for the PR :)

**Comment by grosged** [comment]
> You have some typos that the checks found. Please be sure to fix! Thanks for the PR :)
> 
> Also, this should be set to the `devel` branch, not master. But meh.
> 
> ```
> graphx.asm [3192]:
> 	lb b,ixh
> Processed: lb b,ixh
> Error: illegal instruction.
> ```

Ok, thank you, mateo ! I modify this right now ;)

**Comment by mateoconlechuga** [comment]
Are you even bothering to build this locally haha. Please fix.

```
graphx.asm [3237]:
	lb b,ixh
Processed: lb b,ixh
Error: illegal instruction.
```

**Comment by grosged** [comment]
Actually, I typed my request online : thru my web browser (not the best way, I know)
I'm so far away from being a github expert =D

**Comment by mateoconlechuga** [comment]
all checks look good so going to merge. Thanks again! :)

**Pull request merged**
