### PR TITLE
Update keypadc.asm

### PR DESCRIPTION
**Pull request by grosged**
Optimisation of kb_ScanGroup

### CODE REVIEW

**Comment by adriweb** [comment]
Hi @grosged !

Reminder that unless it's something very specific, only the "devel" branch should be getting PRs. 
However, lately we're basically only working on the LLVM-based toolchain (llvm branch) :D

Could you propose this patch again from here: https://github.com/CE-Programming/toolchain/edit/llvm/src/keypadc/keypadc.asm ?

I'll close this PR and the review can be done on the other one :)
Thanks!

**Comment by adriweb** [comment]
(if you're having trouble proposing the patch with my link, let me know, I can make the PR for you, under your name, with your patch)

**Comment by grosged** [comment]
Ah Okay, thank you Adriweb ;) ... I've just tried the way you told me ;) I hope it's okay for now ..?

**Comment by adriweb** [comment]
yep, should be good !

**Pull request closed without merging**
