### PR TITLE
Add comments for symbols to grahpx.asm

### PR DESCRIPTION
**Pull request by TIny-Hacker**
I added comments for the symbols in the graphx font, to replace the `.` placeholder for symbols previously.

### CODE REVIEW

**Comment by mateoconlechuga** [comment]
Haha nice - but not sure how I feel about this, doesn't this require the file to be utf8 compatible now?

**Comment by adriweb** [comment]
I guess fasmg doesn't care, so it should be fine :)

**Comment by adriweb** [comment]
So, hm, you put the corresponding symbols from the ASCII table? Because for the comments it would be better to just show the most closest-looking symbol in UTF-8.

**Comment by TIny-Hacker** [comment]
I actually did try to find the closest looking symbol (As opposed to corresponding symbols from the ASCII table), it could be I made some mistakes though.

**Review by runer112 — COMMENTED** [review]
I approve of this, assuming that this shouldn't cause any encoding issues. But someone else should probably confirm this.

**Comment by TIny-Hacker** [comment]
I also fixed spacing for character "0x0D" (♪), which should've been 8 pixels instead of 2.

**Review by runer112 — APPROVED** [review]

**Pull request merged**
