### PR TITLE
Added macros to read image dimensions from zx7 data

### PR DESCRIPTION
**Pull request by Iambian**

### CODE REVIEW

**Comment by mateoconlechuga** [comment]
Perhaps different names + a new function?

    gfx_GetZX7SpriteWidth
    gfx_GetZX7SpriteHeight
    gfx_GetZX7SpriteSize

Since

**Comment by Iambian** [comment]
That's all I can think of atm. Suggestions?

**Comment by mateoconlechuga** [comment]
In order for this to be merged, you need to change the base branch to llvm, not master

**Comment by Iambian** [comment]
ok. seems github is telling me that I need to create a new pull request with llvm as the base on my end.

**Comment by adriweb** [comment]
Yes but no, you'll have to push the commit properly from your fork on the llvm branch, otherwise github gets confused :D

**Pull request closed without merging**
