### PR TITLE
Update makefile

### PR DESCRIPTION
**Pull request by SConaway**
Make it more consistent

### CODE REVIEW

**Comment by SConaway** [comment]
Why do you say `RMDIR      = rm -rf $1`, but not `RM      = rm -f $1`?

**Comment by mateoconlechuga** [comment]
They are completely different things. What are you trying to do?

**Comment by SConaway** [comment]
I was trying to make it more consistent for beginners like me.

**Comment by mateoconlechuga** [comment]
You don't even need to touch the makefile system though. Just download an earlier mac release from here: https://github.com/CE-Programming/toolchain/releases/tag/v8.3

**Comment by SConaway** [comment]
I know, but if you're reading the makefile to learn.

**Comment by mateoconlechuga** [comment]
The makefile has absolutely nothing to do with learning.

**Comment by mateoconlechuga** [comment]
Anyway, RMDIR = rm -rf $1, but not RM = rm -f $1 because of how windows treats variables. In the makefile they are used differently:

	$(RM) linker_script
	$(call RMDIR,release)

**Comment by SConaway** [comment]
Oh. Ok.

**Pull request closed without merging**
