### PR TITLE
Improved comments and printTextSmall function

### PR DESCRIPTION
**Pull request by killlmoo**
The comment changes should make the program less confusing. The change to the printTextSmall function will enable text to be printed farther to the right, past 255 pixels.

### CODE REVIEW

**Comment by adriweb** [comment]
Looks good except that line 20 also has to be updated, as we can see by the build failures.

**Comment by killlmoo** [comment]
> Looks good except that line 20 also has to be updated, as we can see by the build failures.

Yep working on that, also trying to learn how to use Github (I am new).

**Comment by adriweb** [comment]
No need to close and reopen PRs each time, when you commit on your branch (where the PR is from), new commits will appear here as well.

**Comment by killlmoo** [comment]
> No need to close and reopen PRs each time, when you commit on your branch (where the PR is from), new commits will appear here as well.

Good to know, I am lost on getting back to my branch to edit it though.

**Comment by adriweb** [comment]
There's a link at the top of the page :)

https://github.com/killlmoo/toolchain/tree/patch-1 in this case

**Comment by killlmoo** [comment]
> There's a link at the top of the page :) https://github.com/killlmoo/toolchain/tree/patch-1 in this case

Figured it out, thanks :).

**Comment by mateoconlechuga** [comment]
I'm rejecting this pr currently because of the use of uint16_t. Please fix that. Also `printTextSmall` should just be removed from the program, it is a worthless function.

**Comment by adriweb** [comment]
BTW, the target branch was changed to "devel" because we use that for all "development" purposes (we try to use the "master" branch to reflect a stable state of things).

And about `uint16_t`, it turns out it's not quite recommended if I understood Mateo correctly, but yeah, the whole `printTextSmall` function can go away anyway :P

**Comment by killlmoo** [comment]
> I'm rejecting this pr currently because of the use of uint16_t. Please fix that. Also `printTextSmall` should just be removed from the program, it is a worthless function.

The `printTextSmall` function needed the uint16_t because the pixel width of the screen is bigger than 255, it is 320. Anyways, the useless function was removed in the end.

**Comment by mateoconlechuga** [comment]
Sorry, I guess I should be more clear. `uint16_t` isn't recommended for use on the ez80 because it isn't a word size, thus increasing the amount of generated code.

**Pull request merged**
