### PR TITLE
update gfx_RotateSpriteC and gfx_RotateSpriteCC

### PR DESCRIPTION
**Pull request by grosged**
Optimised both clockwise & counter-clockwise routines

### CODE REVIEW

**Comment by adriweb** [comment]
The gfx_sprite autotest fails :(

```
Launching autotester on /home/travis/CEdev/examples/gfx_sprite_rotate/autotester.json
/home/travis/CEdev/examples/gfx_sprite_rotate/autotester.json loaded and verified. 2 unique tests found.
	[Test failed!] Hash #1 ("Make sure the rotated sprites are displayed properly") did not match the expected CRC 14098FC (got 1277D1EE).
[Autotest failed] Out of 2 tests attempted, 1 passed, and 1 failed.
```

Can you check what's happening?

**Comment by grosged** [comment]
Thank you for checking, adriweb ;)
I've found the bugs in both routines , then modified them inside my fork ;)

**Comment by adriweb** [comment]
Why close the Pull request, it's automatically updated here when you push on your fork :D

The build & tests are in progress here: https://travis-ci.org/CE-Programming/toolchain/builds/513096282

**Comment by grosged** [comment]
> Why close the Pull request, it's automatically updated here when you push on your fork :D
> 
> The build & tests are in progress here: https://travis-ci.org/CE-Programming/toolchain/builds/513096282
Ah okay, sorry for that :)

**Comment by adriweb** [comment]
Looks like tests are passing - any review before merging?

**Comment by grosged** [comment]
> Looks like tests are passing - any review before merging?
I've done no test at all : just theorical work . I hope everything's will be okay for now

**Comment by adriweb** [comment]
Well, you merged that in devel, but it would have been nice to wait for some comments :P
I guess it's not master and tests pass though so... heh

**Comment by mateoconlechuga** [comment]
Yeah that's what Mateo always does so it's probably fine.

**Pull request merged**
