### PR TITLE
Fix typo in 'Merthsoft'

### PR DESCRIPTION
**Pull request by merthsoft**

### CODE REVIEW

**Comment by runer112** [comment]
What, you don't want to be known as "Methsoft"?

**Comment by runer112** [comment]
This change is obviously fine, but I'm a bit confused by our branch strategy at the moment so I'll hold off until someone more knowledgeable sees this and can verify what the target branch should be.

**Comment by merthsoft** [comment]
Fair! Happy to target a different branch if needed :)

**Comment by adriweb** [comment]
Yeah basically the only real development branch now is llvm, that's what the target should be. I'll change it and merge the PR soon.

**Comment by merthsoft** [comment]
ok I made a mess changing the source. I can make a different branch off of llvm

**Pull request closed without merging**
