### PR TITLE
Update printf.rst

### PR DESCRIPTION
**Pull request by aengus126**
Adds clarification to include the "ti/real.h" library before using the float2str function.

### CODE REVIEW

**Comment by commandblockguy** [comment]
It would probably be more clear to add the #include statement to the code snippet, instead.

**Comment by aengus126** [comment]
I was thinking the same thing. I'm new to github, am I supposed to go back and edit that?

**Comment by commandblockguy** [comment]
You should be able to do that; if not, I can change it myself later today. I personally really don't know how the web UI handles PRs from edits - I believe that was added somewhat recently, and I've always just cloned the repository locally to make changes.

**Comment by adriweb** [comment]
as long as you just make commits (edit files again) in the same branch that the PR is using, the PR will get automatically updated with the new commits.

**Comment by Eeems** [comment]
On the files changed page you can edit a file from the dropdown menu.
image

**Comment by aengus126** [comment]
Okay, I redid it. Thank you guys for the help.

**Pull request merged**
