### PR TITLE
suggest a faster version  of  ScaledSprite_NoClip

### PR DESCRIPTION
**Pull request by grosged**
appears to be 15% faster

### CODE REVIEW

**Comment by MateoConLechuga** [comment]
Technically the null checks on the width and height can be removed; I just assume the user knows what they are doing :P

**Comment by grosged** [comment]
Plus, there was a mistake : read width scale at height scale offset !

**Comment by MateoConLechuga** [comment]
If you would be so kind to move this routine to its new location that would be great :)

**Comment by grosged** [comment]
I will come back

**Pull request closed without merging**
