### PR TITLE
Update graphx.asm

### PR DESCRIPTION
**Pull request by grosged**
Optimisation of gfx_SetTextXY

### CODE REVIEW

**Comment by runer112** [comment]
Clipped text is supported, so X and Y need to be full 24-bit values.

**Comment by adriweb** [comment]
(Reopening to address feedback)

**Comment by runer112** [comment]
I don't believe that this optimization can really be reworked to still apply, as the existing code already looks optimal for full 24-bit values.

**Comment by grosged** [comment]
oh sorry : I did not realised clipped text would be supported.
Full 24-bit for _TextXpos, okay !.. But, concerning _TextYPos, these lines make me think "8 bit" :
ld	hl,0
_TextYPos := $-3
	ld	h,LcdWidth/2
	mlt	hl

**Comment by runer112** [comment]
Yes, that's the unclipped version of the text printing routine. If you look [here](https://github.com/grosged/toolchain/blob/496c8e0f713246b813b473a194d3c24799974c32/src/graphx/graphx.asm#L3302) at the clipped version, though, it reads the full 24-bit X and Y values to pass them on to `gfx_TransparentSprite`.

**Pull request closed without merging**
